### ISSUE TITLE
Editor - Add keyboard shortcuts

### ISSUE THREAD

**Issue by zebulasampedro** [ResearchComputing/OIDE#50]
Add keyboard shortcuts to the editor for existing menu items.

**Comment by zebulasampedro** [comment]
From Saurabh:

> - Ctrl + T to open a new tab
- Ctrl + S to save contents of tab
- Ctrl + N to create a new file
- Handling Delete keypress on a selected file or folder
- Ctrl + C, Ctrl + V/X on the filetree to copy, paste, cut files

**Comment by zebulasampedro** [comment]
Desired shortcuts:
- _Ctrl + s_ to save contents of a tab
- _Ctrl + Shift + s_ to save as
- _Ctrl + w_ to close tab

**Comment by saurabhsood91** [comment]
Completed
